# Generated by Django 4.0.4 on 2022-06-02 21:16

from django.db import migrations
import imagekit.models.fields
import sso.api.res.models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=sso.api.res.models.upload_image),
        ),
    ]
