# Generated by Django 4.0.4 on 2022-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_alter_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
