# Generated by Django 4.0.4 on 2022-06-04 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_background_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
