# Generated by Django 4.0.4 on 2022-06-11 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sso.api.account.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=46, verbose_name='Nama Profil')),
                ('download_speed', models.IntegerField(verbose_name='Kecepatan Unduh')),
                ('upload_speed', models.IntegerField(verbose_name='Kecepatan Unggah')),
                ('download_quota', models.IntegerField(verbose_name='Kuota Unduh')),
                ('upload_quota', models.IntegerField(verbose_name='Kuota Unggah')),
                ('start_ip_address', models.CharField(max_length=15, verbose_name='Rentang Awal Alamat Hotspot')),
                ('end_ip_address', models.CharField(max_length=15, verbose_name='Rentang Akhir Alamat Hotspot')),
                ('keep_alive_timeout', models.DurationField(verbose_name='Waktu Tetap Terkoneksi')),
                ('session_timeout', models.DurationField(verbose_name='Waktu Sesi')),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('mac', models.CharField(max_length=20, unique=True, verbose_name='Alamat MAC')),
                ('ip', models.CharField(max_length=15, verbose_name='Alamat IP')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Masuk Pada')),
                ('token', models.CharField(default=sso.api.account.utils.randStr, max_length=64, verbose_name='Token')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_agent', models.CharField(blank=True, max_length=128, null=True, verbose_name='Agen Pengguna')),
                ('bypass', models.BooleanField(default=False, verbose_name='Bypass Akses')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net.profile', verbose_name='Profil Jaringan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
        ),
    ]
