# Generated by Django 4.0.4 on 2022-06-11 03:26

from django.db import migrations, models
import imagekit.models.fields
import sso.api.account.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Jika tidak aktif, pengguna ini tidak dapat mengakses seluruh sistem', verbose_name='Aktif')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='Merupakan nomor yang terbentuk secara otomatis digunakan secara internal oleh sistem. Nomor ini ditetapkan sekali saat pengguna dibuat.', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('password_last_change', models.DateTimeField(blank=True, null=True, verbose_name='Perubahan kata sandi')),
                ('password_type', models.CharField(choices=[('USER', 'User defined'), ('UUID', 'UUID Number'), ('EID', 'ID Number')], max_length=4, verbose_name='Jenis password tersetel')),
                ('full_name', models.CharField(default='', max_length=70, verbose_name='Nama lengkap')),
                ('eid', models.CharField(blank=True, help_text='Merupakan nomor NIP bagi Siswa dan Alumni, NIP bagi Guru dan Staff', max_length=64, null=True, unique=True, verbose_name='NIS/NIP')),
                ('username', models.CharField(blank=True, help_text='Merupakan nama pengguna yang dapat digunakan untuk masuk. Jika di kosongkan, username akan di buat dari nama lengkap yang disediakan', max_length=70, null=True, unique=True, verbose_name='Username')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('GUEST', 'Tamu'), ('TEACHER', 'Guru'), ('STAFF', 'Staff'), ('ALUMNI', 'Alumni')], default='GUEST', max_length=10, null=True, verbose_name='Peran pengguna')),
                ('permission_type', models.CharField(choices=[('yes', 'Superuser'), ('staff', 'Staff'), ('none', 'Standar')], default='none', max_length=5, verbose_name='Jenis pengguna')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Sediakan nomor telepon dengan format +62XX...', max_length=16, null=True, verbose_name='Telepon')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=sso.api.account.utils.upload_avatar, verbose_name='File foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Diedit pada')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir terlihat pada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-full_name'],
            },
        ),
    ]
