# Generated by Django 4.0.4 on 2022-06-08 02:48

from django.conf import settings
from django.db import migrations
from sso.api.account.models import User

class Migration(migrations.Migration):

    def populate_superuser(*args, **kwargs):
        
        user = User(
            full_name = 'Admin Superuser',
            username = 'admin',
            email = 'admin@' + settings.MAIN_DOMAIN,
            user_type = 'STAFF',
            permission_type = 'yes',
        )

        user.save()
        print('\n\nYour administrator (superuser) account is:')
        print('EMAIL    : ' + user.email)
        print('PASSWORD : ' + str(user.uuid))
        print('\nPlease be careful to save the credentials and change the password immediately on admin console')
        print('Do not rename the username!')
        print('\n')
    
    def revert_superuser(*args, **kwargs):
        User.objects.filter(username = 'admin').delete()

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_superuser, revert_superuser),
    ]
