# Generated by Django 4.0.4 on 2022-06-13 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import sso.api.account.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Jika tidak aktif, pengguna ini tidak dapat mengakses seluruh sistem', verbose_name='Aktif')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='Merupakan nomor yang terbentuk secara otomatis digunakan secara internal oleh sistem. Nomor ini ditetapkan sekali saat pengguna dibuat.', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('password_last_change', models.DateTimeField(blank=True, null=True, verbose_name='Perubahan kata sandi')),
                ('password_type', models.CharField(choices=[('USER', 'User defined'), ('UUID', 'UUID Number'), ('EID', 'ID Number')], max_length=4, verbose_name='Jenis password tersetel')),
                ('full_name', models.CharField(default='', max_length=70, verbose_name='Nama lengkap')),
                ('eid', models.CharField(blank=True, help_text='Merupakan nomor NIP bagi Siswa dan Alumni, NIP bagi Guru dan Staff', max_length=64, null=True, unique=True, verbose_name='NIS/NIP')),
                ('username', models.CharField(blank=True, help_text='Merupakan nama pengguna yang dapat digunakan untuk masuk. Jika di kosongkan, username akan di buat dari nama lengkap yang disediakan', max_length=70, null=True, unique=True, verbose_name='Username')),
                ('permission_type', models.CharField(choices=[('yes', 'Superuser'), ('staff', 'Staff'), ('none', 'Standar')], default='none', max_length=5, verbose_name='Jenis pengguna')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Sediakan nomor telepon dengan format +62XX...', max_length=16, null=True, verbose_name='Telepon')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=sso.api.account.utils.upload_avatar, verbose_name='File foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Diedit pada')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir terlihat pada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Profil')),
                ('name', models.CharField(max_length=46, verbose_name='Nama Profil')),
                ('download_speed', models.BigIntegerField(verbose_name='Kecepatan Unduh')),
                ('upload_speed', models.BigIntegerField(verbose_name='Kecepatan Unggah')),
                ('download_quota', models.BigIntegerField(verbose_name='Kuota Unduh')),
                ('upload_quota', models.BigIntegerField(verbose_name='Kuota Unggah')),
                ('session_timeout', models.DurationField(verbose_name='Waktu Sesi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('shared_user', models.SmallIntegerField(default=1, verbose_name='Jumlah Pengguna Maksimum')),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('mac', models.CharField(max_length=20, unique=True, verbose_name='Alamat MAC')),
                ('ip', models.CharField(max_length=15, verbose_name='Alamat IP')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Masuk Pada')),
                ('token', models.CharField(default=sso.api.account.utils.randStr, max_length=64, verbose_name='Token')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_agent', models.CharField(blank=True, max_length=128, null=True, verbose_name='Agen Pengguna')),
                ('bypass', models.BooleanField(default=False, verbose_name='Bypass Akses')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='Profil Jaringan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile', verbose_name='Profil Pengguna'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
