# Generated by Django 4.0.4 on 2022-06-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import sso.api.account.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('password_last_change', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(default='', max_length=70)),
                ('eid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID Number')),
                ('username', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=sso.api.account.utils.upload_avatar, verbose_name='Photo File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('GUEST', 'Tamu'), ('TEACHER', 'Guru'), ('STAFF', 'Staff'), ('ALUMNI', 'Alumni')], default='GUEST', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, verbose_name='UID')),
                ('uname', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Username')),
                ('upic', models.URLField(blank=True, default='', null=True, verbose_name='Avatar URL')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Name')),
                ('provider', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('GG', 'Google')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
