# Generated by Django 4.0.4 on 2022-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_type',
            field=models.CharField(choices=[('USER', 'User specified'), ('UUID', 'UUID Number'), ('EID', 'ID Number')], default='UUID', max_length=4),
            preserve_default=False,
        ),
    ]
