# Generated by Django 4.0.4 on 2022-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Jika tidak aktif, pengguna ini tidak dapat mengakses seluruh sistem', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_type',
            field=models.CharField(choices=[('yes', 'Superuser'), ('staff', 'Staff'), ('none', 'Standar')], default='none', max_length=5, verbose_name='Jenis pengguna'),
        ),
    ]
