# Generated by Django 4.0.4 on 2022-06-04 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='EID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_type',
            field=models.CharField(choices=[('USER', 'User defined'), ('UUID', 'UUID Number'), ('EID', 'ID Number')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Merupakan nomor yang terbentuk secara otomatis digunakan secara internal oleh sistem. Nomor ini ditetapkan sekali saat pengguna dibuat.', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
