# Generated by Django 4.0.4 on 2022-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active_alter_user_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_last_change',
            field=models.DateField(blank=True, null=True, verbose_name='Perubahan kata sandi'),
        ),
    ]
