# Generated by Django 4.0.4 on 2022-06-04 17:58

from django.db import migrations, models
import imagekit.models.fields
import sso.api.account.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_eid_alter_user_password_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='permission_type',
            field=models.CharField(choices=[('yes', 'Superuser'), ('staff', 'Staff'), ('none', 'Standar')], default='none', max_length=5, verbose_name='Jenis pengguna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=sso.api.account.utils.upload_avatar, verbose_name='File foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eid',
            field=models.CharField(blank=True, help_text='Merupakan nomor NIP bagi Siswa dan Alumni, NIP bagi Guru dan Staff', max_length=64, null=True, unique=True, verbose_name='NIS/NIP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=70, verbose_name='Nama lengkap'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Jika tidak aktif, pengguna ini tidak dapat mengakses seluruh sistem', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diedit pada'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Perubahan kata sandi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_type',
            field=models.CharField(choices=[('USER', 'User defined'), ('UUID', 'UUID Number'), ('EID', 'ID Number')], max_length=4, verbose_name='Jenis password tersetel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Sediakan nomor telepon dengan format +62XX...', max_length=16, null=True, verbose_name='Telepon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Siswa'), ('GUEST', 'Tamu'), ('TEACHER', 'Guru'), ('STAFF', 'Staff'), ('ALUMNI', 'Alumni')], default='GUEST', max_length=10, null=True, verbose_name='Peran pengguna'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Merupakan nama pengguna yang dapat digunakan untuk masuk. Jika di kosongkan, username akan di buat dari nama lengkap yang disediakan', max_length=70, null=True, unique=True, verbose_name='Username'),
        ),
    ]
