# Generated by Django 4.0.4 on 2022-06-14 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='registrant',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
