# Generated by Django 4.0.4 on 2022-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terakhir terlihat pada'),
        ),
    ]
