# Generated by Django 4.0.4 on 2022-06-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_registrant_ip_remove_registrant_mac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='bypass',
        ),
    ]
