# Generated by Django 4.0.4 on 2022-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Perubahan kata sandi'),
        ),
    ]
