# Generated by Django 4.0.4 on 2022-06-05 08:47

from django.db import migrations
from sso.auths.models import SocialOauthProvider as SOP
from sso.auths.utils import populate_sop_from_env, populate_application_oauth, reverse_application_oauth, reverse_sop_from_env

class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sop_from_env, reverse_sop_from_env),
        migrations.RunPython(populate_application_oauth, reverse_application_oauth)
    ]
