# Generated by Django 4.0.4 on 2022-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccountregister',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
