# Generated by Django 4.0.4 on 2022-06-08 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccountregister',
            name='id',
        ),
        migrations.AddField(
            model_name='socialaccountregister',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='UUID', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
