# Generated by Django 4.0.4 on 2022-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_socialaccountregister_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccountregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='socialaccountregister',
            name='uid',
            field=models.CharField(max_length=128, verbose_name='ID'),
        ),
    ]
