# Generated by Django 4.0.4 on 2022-07-04 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_managementaccount'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='UUID', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('semester', models.SmallIntegerField(default=1)),
                ('entry_year', models.IntegerField(default=2022)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('generation_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='UUID', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('major', models.CharField(choices=[('SCIENCE', 'MIPA'), ('SOCIAL', 'IIS'), ('LITERATURE', 'SASTRA')], max_length=10, verbose_name='Major')),
                ('group_number', models.SmallIntegerField()),
                ('class_name', models.CharField(blank=True, max_length=64, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.generation', verbose_name='Generation')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSchool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='UUID', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=128)),
                ('agency', models.CharField(blank=True, choices=[('STATE', 'Negeri'), ('ABROAD', 'Luar Negeri'), ('PRIVATE', 'Swasta')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('PESANTREN', 'Pesantren'), ('BOARDING', 'Boarding School'), ('FORMAL', 'Formal'), ('PAKET', 'Paket')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=128)),
                ('stage', models.CharField(blank=True, choices=[('JHS', 'SMP Sederajat'), ('SHS', 'SMA Sederajat'), ('ES', 'SD Sederajat')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('managementaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.managementaccount')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group', verbose_name='Group')),
                ('previous_school_junior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior', to='student.previousschool', verbose_name='Previous School (Junior)')),
                ('previous_school_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='student.previousschool', verbose_name='Previous School (Transfer)')),
            ],
            bases=('account.managementaccount',),
        ),
    ]
