# Generated by Django 4.0.4 on 2022-07-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_generation_is_graduated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='generation_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='class_name',
            new_name='name',
        ),
    ]
