# Generated by Django 4.0.4 on 2022-07-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_rename_generation_name_generation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='head_class_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_class', to='student.student', verbose_name='Ketua Kelas'),
        ),
        migrations.AlterField(
            model_name='group',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.generation', verbose_name='Angkatan'),
        ),
        migrations.AlterField(
            model_name='group',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher', verbose_name='Wali Kelas'),
        ),
        migrations.AlterField(
            model_name='group',
            name='major',
            field=models.CharField(choices=[('SCIENCE', 'MIPA'), ('SOCIAL', 'IIS'), ('LITERATURE', 'SASTRA')], max_length=10, verbose_name='Jurusan'),
        ),
    ]
