# Generated by Django 4.0.4 on 2022-07-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_managementaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('managementaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.managementaccount')),
            ],
            bases=('account.managementaccount',),
        ),
    ]
